config/routes.rb
Rails.application.routes.draw do
  scope "/gengo" do
    resources :localizations do
      collection do
        post :import
        get :test_import
        post :update_job
        post :send_to_gengo
      end
    end
  end
end

app/models/localization.rb
class Localization < ActiveRecord::Base
  attr_accessible :locale, :path, :value, :status, :job_id, :data
  before_validation :set_data
  
  serialize :data, JSON
  
  validates :locale, :path, :value, presence: true
  validates :path, uniqueness: { scope: :locale }
  validates_each :data do |record, attr, value|
    record.errors.add(attr, 'must be a Hash') unless value.kind_of?(Hash)
  end
  
  scope :approved, ->{ where(status: "approved") }
  
  def translated_value
    data["body_tgt"]
  end
  
  def set_data
    self.data ||= {}
  end
end

app/controllers/localizations_controller.rb
class LocalizationsController < ApplicationController
  # GET /localizations
  # GET /localizations.json
  def index
    @localizations = Localization.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @localizations }
    end
  end

  # GET /localizations/1
  # GET /localizations/1.json
  def show
    @localization = Localization.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @localization }
    end
  end

  # GET /localizations/new
  # GET /localizations/new.json
  def new
    @localization = Localization.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @localization }
    end
  end

  # GET /localizations/1/edit
  def edit
    @localization = Localization.find(params[:id])
  end

  # POST /localizations
  # POST /localizations.json
  def create
    @localization = Localization.new(params[:localization])

    respond_to do |format|
      if @localization.save
        format.html { redirect_to @localization, notice: 'Localization was successfully created.' }
        format.json { render json: @localization, status: :created, location: @localization }
      else
        format.html { render action: "new" }
        format.json { render json: @localization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /localizations/1
  # PUT /localizations/1.json
  def update
    @localization = Localization.find(params[:id])

    respond_to do |format|
      if @localization.update_attributes(params[:localization])
        format.html { redirect_to @localization, notice: 'Localization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @localization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /localizations/1
  # DELETE /localizations/1.json
  def destroy
    @localization = Localization.find(params[:id])
    @localization.destroy

    respond_to do |format|
      format.html { redirect_to localizations_url }
      format.json { head :no_content }
    end
  end
  
  def import
    @localization_factory = LocalizationFactory.new.from_list(localizations_list)
    
    render json: @localization_factory.to_json
  end
  
  def update_job
    job = JSON.parse(params[:job])
    localization = Localization.find_by_id(job["custom_data"])
    localization.update_attributes(status: job["status"], job_id: job["job_id"], data: job)
    render text: "ok"
  end
  
  def send_to_gengo
    @localizations = Localization.where(job_id: nil)
    package = TranslationPackage.new(@localizations, update_job_localizations_url)
    package.send_to_gengo
    redirect_to localizations_path
  end
  
  private
  
  def localizations_list
    params[:localizations_list] || []
  end
end

app/helpers/localizations_helper.rb
module LocalizationsHelper
end

app/views/localizations/_form.html.erb
<%= form_for(@localization) do |f| %>
  <% if @localization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@localization.errors.count, "error") %> prohibited this localization from being saved:</h2>

      <ul>
      <% @localization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :path %><br />
    <%= f.text_field :path %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :locale %><br />
    <%= f.text_field :locale %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/localizations/edit.html.erb
<h1>Editing localization</h1>

<%= render 'form' %>

<%= link_to 'Show', @localization %> |
<%= link_to 'Back', localizations_path %>

app/views/localizations/import.html.erb
<h3>Tried to import <%= @localization_factory.localizations.size %> localizations</h3>
<h4><%= @localization_factory.valid_localizations.size %> valid localizations were imported</h4>
<p><%= @localization_factory.invalid_localizations.size %> invalid localizations were not imported due to errors</p>

app/views/localizations/index.html.erb
<div class="container">
  <h1>Listing localizations</h1>

  <table class="table table-striped">
    <tr>
      <th>Locale</th>
      <th>Path</th>
      <th>Value</th>
      <th>Job ID</th>
      <th>Status</th>
      <th>Translated Value</th>
    </tr>

  <% @localizations.each do |localization| %>
    <tr>
      <td><%= localization.locale %></td>
      <td><%= localization.path %></td>
      <td><%= localization.value %></td>
      <td><%= localization.job_id %></td>
      <td><%= localization.status %></td>
      <td><%= localization.translated_value %></td>
    </tr>
  <% end %>
  </table>

  <br />

  <%= link_to 'New Localization', new_localization_path, class: "btn btn-primary" %>

  <!-- Button trigger modal -->
  <button type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal">
    Send to Gengo
  </button>

  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Send to Gengo?</h4>
        </div>
        <div class="modal-body">
          <h4>You have selected <%= @localizations.count %> keys to send to Gengo.</h4>
          <p class="text-danger"><strong>Warning!</strong> This action can not be undone!</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <%= link_to 'Send', send_to_gengo_localizations_path, method: :post, class: "btn btn-success" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/localizations/new.html.erb
<h1>New localization</h1>

<%= render 'form' %>

<%= link_to 'Back', localizations_path %>

app/views/localizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Path:</b>
  <%= @localization.path %>
</p>

<p>
  <b>Value:</b>
  <%= @localization.value %>
</p>

<p>
  <b>Locale:</b>
  <%= @localization.locale %>
</p>


<%= link_to 'Edit', edit_localization_path(@localization) %> |
<%= link_to 'Back', localizations_path %>

app/views/localizations/test_import.html.erb
<%= form_tag(import_localizations_path) do %>
  <%= text_area_tag :localizations_list %>
  <%= submit_tag "Send", id: "test_import_submit" %>
<% end %>

<p>In order to import files, you need to send them in the following format:</p>
<p><%= { localizations_list: [{ value: "Value", path: "path.to.some.where", locale: "en" }]}.to_json %></p>

<div class="result">
</div>

<script>
  $('#test_import_submit').click(function(event) {
    event.preventDefault();
    var localizationsList = $('#localizations_list').val();
    $.ajax({
      type: "POST",
      url: '<%= import_localizations_url %>',
      contentType: 'application/json',
      accept: 'text/html',
      data: localizationsList,
      dataType: 'json',
      success: function(data) {
        $('.result').html(data);
      }
    })
      .done(function (data) {
        result = 'Tried to import ' + data.localizations.length + '. ';
        result += 'Succesfull: ' + data.valid_localizations.length + '. ';
        result += 'Failed: ' + data.invalid_localizations.length + '. ';
        $('.result').text(result);
        
        setTimeout(function(){
          $('.result').text('');
        }, 5000);
      });
  });
</script>